// client/src/components/Nav/index.tsx
"use client";

import { ReactNode, useEffect, useState } from "react";
import { FiX, FiMenu } from "react-icons/fi";
import { GoHomeFill } from "react-icons/go";
import { HiMiniUsers } from "react-icons/hi2";
import { FaListUl } from "react-icons/fa6";
import { useSession } from "next-auth/react";
import { url } from "gravatar";
import Link from "next/link";
import { usePathname } from "next/navigation";

interface Props {
  children: ReactNode;
}

function Nav({ children }: Props) {
  const [active, setActive] = useState(false);
  const { data, status } = useSession();
  const pathname = usePathname();

  const perms = ["Invitado", "Profesor", "Administrador"];

  const items = [
    {
      label: "Inicio",
      path: "/dash",
      icon: <GoHomeFill />,
    },
    {
      label: "Grados",
      path: "/dash/grades",
      icon: <FaListUl />,
    },
    {
      label: "Usuarios",
      path: "/dash/users",
      icon: <HiMiniUsers />,
    },
    {
      label: "Asistencias",
      path: "/dash/assistances",
      icon: <FaListUl />,
    },
  ];

  const handleActive = () => setActive(!active);

  return (
    <div className="flex flex-col w-full h-full bg-slate-950">
      <nav className="flex gap-3 px-3 py-3 items-center">
        <button
          className="bg-slate-800 border-2 border-slate-600 px-2 py-1 rounded-md text-2xl text-white xs:hidden"
          onClick={handleActive}
        >
          {!active ? <FiMenu /> : <FiX />}
        </button>
        <p className="font-medium text-xl text-white">Sistema de Asistencias</p>
      </nav>
      <div className="relative flex flex-row w-full h-full justify-center items-center overflow-hidden">
        {/* Sidebar */}
        <nav
          className={`absolute flex flex-col top-0 left-0 w-full h-full transition-all duration-500  justify-between bg-slate-950 overflow-y-auto ${
            active ? "max-w-full" : "max-w-0"
          } xs:relative xs:max-w-64`}
        >
          <ul className="flex flex-col p-3 gap-3">
            {items.map(({ label, icon, path }, key) => (
              <li key={key}>
                <Link
                  href={path}
                  className={`flex items-center gap-3 px-3 py-2 text-slate-300 ${
                    path === pathname
                      ? "bg-slate-800 !text-slate-50"
                      : "bg-slate-700"
                  } rounded-xl transition-colors duration-300 cursor-default text-text-nowrap hover:bg-slate-500`}
                  onClick={() => setActive(false)}
                >
                  {icon} {label}
                </Link>
              </li>
            ))}
          </ul>
          {status === "authenticated" && (
            <div className="flex gap-3 items-center px-3 py-2">
              <img
                src={url(data!.user.email, { size: "64" })}
                alt={data.user.email}
                className="rounded-full w-16 h-16"
              />

              <div className="flex flex-col">
                <p className="text-white text-nowrap pointer-events-none">
                  {data?.user.firstName} {data?.user.lastName}
                </p>
                <span className="text-slate-300 text-xs text-nowrap mb-1 pointer-events-none">
                  {data?.user.email}
                </span>
                <span className="text-white text-xs font-bold pointer-events-none">
                  {perms[data!.user.permissionsLevel]}
                </span>
              </div>
            </div>
          )}
        </nav>
        <div className="w-full h-full px-2 pb-2">
          <div className="w-full h-full bg-slate-300 rounded-2xl p-2 overflow-y-auto overflow-x-hidden">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Nav;

// client/src/app/components/nav/nav.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import {
  featherList,
  featherUsers,
  featherMenu,
  featherX,
  featherLogOut,
} from '@ng-icons/feather-icons';
import { heroSquares2x2 } from '@ng-icons/heroicons/outline';
import { UserResponse } from 'src/app/core/interfaces/api';
import { UsersService } from 'src/app/core/services/users.service';
import { url } from 'gravatar';
import { SessionService } from 'src/app/core/services/session.service';

@Component({
  selector: 'app-nav',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, NgIconComponent],
  providers: [provideIcons({ featherMenu, featherX, featherLogOut })],
  templateUrl: './nav.component.html',
})
export class NavComponent implements OnInit {
  active: boolean = false;
  user!: UserResponse;

  routes = [
    {
      label: 'Inicio',
      url: '/',
      icon: heroSquares2x2,
    },
    {
      label: 'Usuarios',
      url: '/users',
      icon: featherUsers,
    },
    {
      label: 'Grados',
      url: '/grades',
      icon: featherList,
    },
  ];

  constructor(
    private usersService: UsersService,
    private session: SessionService
  ) {}

  ngOnInit(): void {
    this.usersService.whoami().subscribe((u) => (this.user = u));
  }

  getAvatarUrl() {
    return url(this.user.email, {
      size: '48',
    });
  }

  toggleActive() {
    this.active = !this.active;
  }

  logOut() {
    this.session.signOut();
  }
}

<div class="relative w-full h-full flex overflow-hidden">
  <nav
    class="bg-slate-900 w-full {{
      active ? 'max-w-xs' : 'max-w-0'
    }} h-full absolute top-0 left-0 z-50 overflow-hidden transition-all duration-300 md:relative md:!max-w-xs"
  >
    <div class="flex justify-between items-center w-full px-3 py-2 md:hidden">
      <h5 class="text-slate-50 text-xl">Navegación</h5>
      <button
        type="button"
        (click)="toggleActive()"
        class="text-3xl outline-none flex justify-center items-center p-1 rounded-full bg-slate-800 text-nowrap text-slate-50"
      >
        @if (active) {
        <ng-icon name="featherX" />
        } @else {
        <ng-icon name="featherMenu" />
        }
      </button>
    </div>
    <div class="flex flex-col justify-between h-full">
      <ul>
        @for (item of routes; track $index) {
        <li>
          <a
            [routerLink]="item.url"
            [routerLinkActive]="'!bg-slate-800 border-r-4 border-r-blue-400'"
            [routerLinkActiveOptions]="{ exact: true }"
            class="flex items-center gap-3 text-slate-50 px-3 py-5 cursor-default transition-colors duration-300 hover:bg-slate-800 hover:bg-opacity-50"
            (click)="toggleActive()"
          >
            <ng-icon [svg]="item.icon" /> {{ item.label }}
          </a>
        </li>
        }
      </ul>
      <a
        class="flex items-center gap-3 text-slate-50 px-3 py-5 cursor-default transition-colors duration-300 hover:bg-slate-800"
        (click)="logOut()"
      >
        <ng-icon name="featherLogOut" /> Cerrar sesión
      </a>
    </div>
  </nav>
  <div class="w-full h-full">
    <nav class="flex justify-between items-center px-3 py-2 h-16 bg-slate-900">
      <button
        type="button"
        (click)="toggleActive()"
        class="flex items-center justify-center text-3xl outline-none text-slate-50 bg-slate-900 px-3 py-1 rounded-xl md:hidden"
      >
        @if (active) {
        <ng-icon name="featherX" />
        } @else {
        <ng-icon name="featherMenu" />
        }
      </button>

      <div class="flex justify-end w-full items-center gap-3">
        @if (user) {
        <img
          [src]="getAvatarUrl()"
          [alt]="user.email"
          class="rounded-full w-12"
        />

        <div>
          <p class="text-slate-50">{{ user.firstName }} {{ user.lastName }}</p>
          <p class="text-slate-400 text-xs">{{ user.email }}</p>
        </div>
        }
      </div>
    </nav>

    <!-- children -->
    <div class="w-full h-full bg-slate-950 overflow-y-auto">
      <ng-content />
    </div>
  </div>
</div>
