// client/src/app/login/page.tsx
"use client";

import { signIn } from "next-auth/react";
import { useRouter, useSearchParams } from "next/navigation";
import { ChangeEvent, useState } from "react";

export default function Login() {
  const [error, setError] = useState<string>("");
  const [credentials, setCredentials] = useState({
    email: "",
    password: "",
  });
  const [disable, setDisable] = useState(false);
  const router = useRouter();
  const query = useSearchParams(),
    callbackUrl = query.get("callbackUrl");

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError("");
    setDisable(true);

    const responseNextAuth = await signIn("credentials", {
      ...credentials,
      redirect: false,
    });

    if (responseNextAuth?.error) {
      setError(responseNextAuth.error);
      setDisable(false);
      return;
    }

    router.push(callbackUrl || "/");
  };

  const handleTyping = (e: ChangeEvent<HTMLInputElement>) => {
    setCredentials({ ...credentials, [e.target.name]: e.target.value });
  };

  return (
    <main className="flex justify-center items-center bg-slate-950 w-full h-full">
      <form
        className="flex flex-col gap-4 bg-slate-700 max-w-xs w-full rounded-2xl py-3 px-6"
        onSubmit={handleSubmit}
      >
        <h1 className="text-center text-3xl text-slate-50 font-bold">
          Iniciar sesión
        </h1>

        {error && (
          <div className="bg-red-100 bg-opacity-90 border-2 border-red-600 rounded-xl px-3 py-2">
            {error}
          </div>
        )}

        <label className="text-slate-50">
          Correo:
          <input
            className="px-2 py-1 rounded-lg bg-slate-800 outline-none text-slate-50 border-2 border-slate-800 transition-colors duration-300 hover:border-blue-200 focus:border-blue-400 disabled:cursor-not-allowed disabled:text-slate-400"
            type="text"
            name="email"
            onChange={handleTyping}
            required
            disabled={disable}
          />
        </label>
        <label className="text-slate-50">
          Contraseña:
          <input
            className="px-2 py-1 rounded-lg bg-slate-800 outline-none text-slate-50 border-2 border-slate-800 transition-colors duration-300 hover:border-blue-200 focus:border-blue-400 disabled:cursor-not-allowed disabled:text-slate-400"
            type="password"
            name="password"
            onChange={handleTyping}
            required
            disabled={disable}
          />
        </label>

        <button
          className="px-3 py-2 bg-blue-300 rounded-xl transition-colors duration-300 hover:bg-blue-400 disabled:cursor-not-allowed disabled:bg-slate-400"
          type="submit"
          disabled={disable}
        >
          Iniciar sesión
        </button>
      </form>
    </main>
  );
}

// client/src/app/pages/auth/login.component.ts
import { Component, OnInit } from '@angular/core';
import {
  FormControl,
  FormGroup,
  FormSubmittedEvent,
  ReactiveFormsModule,
} from '@angular/forms';
import { EMPTY, catchError } from 'rxjs';
import { SessionService } from '@services/session.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './login.component.html',
})
export class LoginComponent implements OnInit {
  loginForm = new FormGroup({
    email: new FormControl<string>(''),
    password: new FormControl<string>(''),
  });
  errorMessage?: string;
  disabled: boolean = false;

  constructor(private service: SessionService, private router: Router) {}

  ngOnInit(): void {
    this.loginForm.events.subscribe((e) => {
      if (e instanceof FormSubmittedEvent) {
        this.errorMessage = undefined;
        const { email, password } = e.source.value;
        // Disable form
        this.loginForm.disable();
        this.disabled = true;

        // SignIn Request
        this.service
          .signIn({ email, password })
          .pipe(
            catchError((err: string) => {
              // Enable form
              this.errorMessage = err;
              this.loginForm.enable();
              this.disabled = false;

              return EMPTY;
            })
          )
          .subscribe((e) => {
            this.service.saveTokens(e);
            this.router.navigateByUrl('/');
          });
      }
    });
  }
}

<div class="bg-slate-950 w-full h-full flex justify-center items-center">
  <form
    [formGroup]="loginForm"
    class="bg-slate-700 w-full max-w-80 rounded-3xl p-3"
  >
    <legend class="uppercase text-slate-50 text-2xl text-center mb-4">
      Iniciar sesión
    </legend>

    @if (errorMessage) {
    <p class="px-2 py-3 rounded-xl bg-red-200 border-2 border-red-600 mb-4">
      {{ errorMessage }}
    </p>
    }

    <fieldset class="flex flex-col gap-3 mb-5">
      <label class="text-slate-50 flex flex-col gap-1">
        E-mail:
        <input
          type="email"
          formControlName="email"
          class="px-2 py-1 rounded-lg bg-slate-800 outline-none text-slate-50 border-2 border-slate-800 transition-colors duration-300 hover:border-blue-200 focus:border-blue-400 disabled:cursor-not-allowed disabled:text-slate-400"
          required
        />
      </label>
      <label class="text-slate-50 flex flex-col gap-1">
        Contraseña:
        <input
          type="password"
          formControlName="password"
          class="px-2 py-1 rounded-lg bg-slate-800 outline-none text-slate-50 border-2 border-slate-800 transition-colors duration-300 hover:border-blue-200 focus:border-blue-400 disabled:cursor-not-allowed disabled:text-slate-400"
          required
        />
      </label>
    </fieldset>
    <button
      type="submit"
      class="px-3 py-2 rounded-lg bg-blue-300 w-full transition-colors duration-300 hover:bg-blue-400 disabled:bg-gray-300"
      [disabled]="disabled"
    >
      Aceptar
    </button>
  </form>
</div>
